package main

import (
	"context"
	"time"

	"github.com/kuzzrus/keenetic-xray-go/internal/georanges"
	"github.com/kuzzrus/keenetic-xray-go/internal/knownranges"
)

// georangesSourceURL serves this project's own generated Russia IPv4
// list (internal/georanges/data/ru-ipv4.txt, regenerated by
// cmd/georanges-gen from the RIR delegated-statistics files, kept fresh
// by .github/workflows/georanges-update.yml) off raw.githubusercontent.com.
//
// Was country-ip-blocks.hackinggate.com (a third party's own generated
// list) until 2026-09-16: confirmed live that host is simply unreachable
// from inside Russia -- every fetch died "context deadline exceeded ...
// while awaiting headers", never once succeeding, so no cache was ever
// written and ExcludedRangeLookup matched nothing for the feature's
// entire first day. raw.githubusercontent.com is not a guess -- this
// project's own install.sh and internal/knownranges already fetch from
// it successfully, self-update included. See the russia-ip-exclusion-
// plan memory for the incident and internal/georanges/embedded.go for
// the other half of this fix (a build-time snapshot, so the veto no
// longer depends on this URL being reachable at all on first boot).
const georangesSourceURL = "https://raw.githubusercontent.com/kuzzrus/keenetic-xray-go/main/internal/georanges/data/ru-ipv4.txt"

// georangesRefreshInterval mirrors knownRangesRefreshInterval -- the
// upstream source updates on weekdays at most.
const georangesRefreshInterval = 24 * time.Hour

// georangesBootstrapFetchTimeout bounds georangesBootstrap's own network
// fetch attempt (only reached when no cache exists yet) -- shorter than
// runGeorangesRefresh's usual 2-minute ceiling so a dead network can't
// hold up daemon startup.
//
// Was 8s until 2026-09-16, which was simply too tight: on the real
// router this timed out every time ("georanges: refresh failed:
// context deadline exceeded"), leaving the table empty -- and since a
// failed attempt then waited a full georangesRefreshInterval to retry,
// the Russian-exclusion veto was silently inert for a whole day at a
// stretch. ~200KB over a router's WAN while everything else is also
// starting up needs more room than that. Still bounded: this only ever
// runs on a router that has never successfully fetched the list, and
// georangesRetryBackoff below is what actually guarantees we get it.
const georangesBootstrapFetchTimeout = 25 * time.Second

// georangesRetryBackoff is how long georangesRefreshLoop waits between
// attempts while it still has no table at all -- growing from the first
// value to the last and then staying there, rather than jumping
// straight to georangesRefreshInterval.
//
// The whole point: an empty table means ExcludedRangeLookup silently
// matches nothing, so the veto is off. Waiting 24h to retry turned a
// transient fetch failure into a day-long outage of a safety feature,
// with one log line as the only evidence (and that line scrolls out of
// `keenetic-xray logs` within minutes on a busy router). Backoff rather
// than a flat retry so a genuinely unreachable source doesn't fill the
// log: roughly nine attempts in the first hour, then every 15 minutes.
var georangesRetryBackoff = []time.Duration{
	30 * time.Second,
	time.Minute,
	2 * time.Minute,
	5 * time.Minute,
	15 * time.Minute,
}

// georangesBootstrap makes sure ExcludedRangeLookup has *some* real
// table loaded before returning -- cache if one exists (near-instant,
// local disk), else the snapshot embedded in this binary
// (internal/georanges.Embedded, also near-instant, zero network
// involved), topped up by one best-effort bounded network fetch either
// way. Called synchronously from main, BEFORE adaptiveRouteClassifyLoop
// is spawned, specifically so ClrFast/ClrSoft's veto is never racing its
// own data source.
//
// Found live (2026-09-16), three times over, each fix closing a
// narrower version of the same mistake: georangesRefreshLoop used to
// load state in its own independent goroutine, racing
// adaptiveRouteClassifyLoop's -- synchronizing the two here (rather than
// just shortening the delay before that goroutine's own attempt) closed
// the *race*. But a synchronized fetch that simply fails leaves the
// same hole: this router's own network turned out unable to reach the
// list's original host at all, so the "one bounded fetch" this function
// used to rely on as its entire strategy never once succeeded, and
// ExcludedRangeLookup matched nothing all day despite the feature
// looking fully configured. The embedded fallback below closes *that*
// gap -- the veto no longer depends on any network call succeeding,
// ever, ever having to. A confirmed address stays redirected for its
// full ~6h OKTTL regardless of when real data finally loads, which is
// exactly why "eventually" was never good enough here. See the
// russia-ip-exclusion-plan memory for the full incident.
//
// Deliberately unconditional (not gated on cfg.AdaptiveRoute.Enabled):
// that flag can be toggled on later, live, without a daemon restart
// (adaptiveRouteClassifyLoop is already always running, it just no-ops
// while disabled) -- gating this on today's Enabled value would just
// move the same race to "whenever the operator turns adaptive routing
// on", not remove it. The cost of always paying this is small and
// mostly one-time in practice: georangesBootstrapFetchTimeout only
// matters on a router that has never successfully fetched this table
// before, every later restart finds a cache and returns near-instantly.
func georangesBootstrap(ctx context.Context, logf func(string, ...any)) {
	if raw, err := knownranges.LoadCacheRaw(georangesCachePath()); err == nil {
		georanges.SetCurrent(georanges.Parse(raw))
		logf("georanges: loaded %d Russian ranges from cache", georanges.CurrentLen())
		return
	}

	embedded := georanges.Embedded()
	georanges.SetCurrent(embedded)
	logf("georanges: no cache on disk -- using %d Russian ranges embedded in this build while a fresher copy is fetched", embedded.Len())

	bctx, cancel := context.WithTimeout(ctx, georangesBootstrapFetchTimeout)
	defer cancel()
	runGeorangesRefresh(bctx, logf)
}

// georangesRefreshLoop keeps internal/georanges' process-wide table
// fresh going forward. georangesBootstrap (called synchronously before
// this is even spawned, see main.go) already made the first load
// attempt, so from here on this either tops the table up daily or, if
// there is still no table at all, keeps retrying on
// georangesRetryBackoff until there is one -- see that var's doc
// comment for why the difference matters so much.
func georangesRefreshLoop(ctx context.Context, logf func(string, ...any)) {
	retries := 0
	next := func() time.Duration {
		if georanges.CurrentLen() > 0 {
			retries = 0
			return georangesRefreshInterval
		}
		d := georangesRetryBackoff[min(retries, len(georangesRetryBackoff)-1)]
		retries++
		return d
	}

	timer := time.NewTimer(next())
	defer timer.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-timer.C:
		}
		runGeorangesRefresh(ctx, logf)
		timer.Reset(next())
	}
}

func runGeorangesRefresh(ctx context.Context, logf func(string, ...any)) {
	rctx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()
	raw, err := knownranges.FetchRaw(rctx, georangesSourceURL)
	if err != nil {
		logf("georanges: refresh failed: %v", err)
		return
	}
	table := georanges.Parse(raw)
	if table.Len() == 0 {
		logf("georanges: refresh returned no usable ranges -- keeping the previous copy")
		return
	}
	if err := knownranges.SaveCacheRaw(georangesCachePath(), raw); err != nil {
		// The freshly fetched table is still good even if persisting it
		// failed -- no reason to throw away a successful fetch over a
		// disk write error, only the next restart loses the head start.
		logf("georanges: could not persist cache: %v", err)
	}
	georanges.SetCurrent(table)
	logf("georanges: refreshed, %d Russian ranges loaded", table.Len())
}
