package georanges

import _ "embed"

// embeddedRaw is internal/georanges/data/ru-ipv4.txt, baked into the
// binary at build time -- a point-in-time snapshot regenerated by
// cmd/georanges-gen, refreshed daily by
// .github/workflows/georanges-update.yml.
//
// Exists as the final fallback under the cache-then-network chain
// (cmd/keenetic-xray's georangesBootstrap): confirmed live (2026-09-16)
// that a background fetch alone is not a reliable enough foundation for
// a safety veto -- the original third-party host was simply unreachable
// from inside Russia ("context deadline exceeded ... while awaiting
// headers", every attempt, all day), and even after switching to our
// own repo, a router's very first boot has no cache yet and network
// conditions at that exact moment are the one thing this project has
// the least control over. With this, ExcludedRangeLookup has real data
// from the first classify tick on every install, including one that has
// never once reached the network successfully -- the background refresh
// (still tried right after, and daily thereafter) is genuinely just
// what it should have been all along: keeping already-good data fresh,
// not a precondition for the veto doing anything at all. See the
// russia-ip-exclusion-plan memory for the day this went wrong.
//
//go:embed data/ru-ipv4.txt
var embeddedRaw string

// Embedded parses and returns the snapshot built into this binary.
// Cheap enough to call more than once (~11k lines, done once at
// startup) -- no reason to cache the parsed form separately from
// whatever the caller does with it.
func Embedded() *Table { return Parse(embeddedRaw) }
