// Package presets exposes the curated per-service routing lists embedded
// from data/ (generated by cmd/geo-gen, refreshed daily in CI). The
// router binary reads them to offer "ready-made lists" in the bot's
// 📦 Готовые списки screen and `keenetic-xray routes preset …`, and to
// tell an already-applied list from an out-of-date one.
package presets

import (
	"embed"
	"encoding/json"
	"sort"
	"strings"
	"sync"
)

//go:embed data/manifest.json data/*.lst
var files embed.FS

// Preset is one row of data/manifest.json: a domain list or its CIDR
// companion for a service. Name is the list id ("youtube", "youtube-ip");
// Service groups the pair ("youtube"). Rev is a short hash of the list
// content, used to detect that an applied list has drifted from the
// shipped one.
type Preset struct {
	Name     string   `json:"name"`
	Service  string   `json:"service"`
	Title    string   `json:"title"`
	Category string   `json:"category"`
	Kind     string   `json:"kind"` // "domains" | "cidr"
	Count    int      `json:"count"`
	Rev      string   `json:"rev"`
	Sources  []string `json:"sources"`
}

type manifest struct {
	Version    int      `json:"version"`
	Generated  string   `json:"generated"`
	Categories []string `json:"categories"`
	Presets    []Preset `json:"presets"`
}

var (
	once   sync.Once
	loaded manifest
	byName map[string]Preset
)

func load() {
	once.Do(func() {
		raw, err := files.ReadFile("data/manifest.json")
		if err != nil {
			return
		}
		_ = json.Unmarshal(raw, &loaded)
		byName = make(map[string]Preset, len(loaded.Presets))
		for _, p := range loaded.Presets {
			byName[p.Name] = p
		}
	})
}

// Generated is the date stamp of the embedded manifest ("2006-01-02").
func Generated() string {
	load()
	return loaded.Generated
}

// All returns every preset, sorted by name.
func All() []Preset {
	load()
	out := append([]Preset(nil), loaded.Presets...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// Find returns the preset row for a list id ("youtube" / "youtube-ip").
func Find(name string) (Preset, bool) {
	load()
	p, ok := byName[strings.ToLower(strings.TrimSpace(name))]
	return p, ok
}

// Category groups presets for the bot menu.
type Category struct {
	Name    string
	Presets []Preset // domain presets only ("-ip" companions excluded), sorted by title
}

// ByCategory returns the domain presets grouped by category -- categories
// in the manifest's declared order (with any stragglers appended), and
// presets within a category sorted by title. CIDR companions
// ("<svc>-ip") are left out; the UI offers them as a toggle on the
// domain preset via HasCIDR.
func ByCategory() []Category {
	load()
	group := map[string][]Preset{}
	var order []string
	for _, p := range loaded.Presets {
		if p.Kind != "domains" {
			continue
		}
		if _, ok := group[p.Category]; !ok {
			order = append(order, p.Category)
		}
		group[p.Category] = append(group[p.Category], p)
	}

	seq := loaded.Categories
	if len(seq) == 0 {
		seq = order
	}
	seen := map[string]bool{}
	var cats []Category
	add := func(name string) {
		if seen[name] {
			return
		}
		ps := group[name]
		if len(ps) == 0 {
			return
		}
		seen[name] = true
		sort.Slice(ps, func(a, b int) bool { return ps[a].Title < ps[b].Title })
		cats = append(cats, Category{Name: name, Presets: ps})
	}
	for _, c := range seq {
		add(c)
	}
	for _, c := range order { // any category missing from the declared order
		add(c)
	}
	return cats
}

// HasCIDR reports whether a "<service>-ip" companion list exists for the
// given domain-preset name.
func HasCIDR(name string) bool {
	load()
	_, ok := byName[strings.ToLower(strings.TrimSpace(name))+"-ip"]
	return ok
}

// Entries returns the list body for a preset id: domains or CIDRs, one
// per line, comments and blanks stripped. Order is as stored (already
// sorted by the generator).
func Entries(name string) ([]string, bool) {
	load()
	name = strings.ToLower(strings.TrimSpace(name))
	if _, ok := byName[name]; !ok {
		return nil, false
	}
	raw, err := files.ReadFile("data/" + name + ".lst")
	if err != nil {
		return nil, false
	}
	var out []string
	for _, ln := range strings.Split(string(raw), "\n") {
		ln = strings.TrimSpace(ln)
		if ln == "" || strings.HasPrefix(ln, "#") {
			continue
		}
		out = append(out, ln)
	}
	return out, true
}
