// Package presets exposes the curated per-service routing lists embedded
// from data/ (generated by cmd/geo-gen, refreshed daily in CI). The
// router binary reads them to offer "ready-made lists" in the bot's
// 📦 Готовые списки screen and `keenetic-xray routes preset …`, and to
// tell an already-applied list from an out-of-date one.
//
// The embedded copy is the baseline. A router can also keep a live
// overlay directory (see SetOverlay + Refresh): when it holds a
// manifest.json, the package serves the overlay and falls back to the
// embed per-file. That's how a router picks up the daily repo refresh
// without a reinstall.
package presets

import (
	"embed"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
)

//go:embed data/manifest.json data/*.lst
var files embed.FS

// Preset is one row of data/manifest.json: a domain list or its CIDR
// companion for a service. Name is the list id ("youtube", "youtube-ip");
// Service groups the pair ("youtube"). Rev is a short hash of the list
// content, used to detect that an applied list has drifted from the
// shipped one.
type Preset struct {
	Name     string   `json:"name"`
	Service  string   `json:"service"`
	Title    string   `json:"title"`
	Category string   `json:"category"`
	Kind     string   `json:"kind"` // "domains" | "cidr"
	Count    int      `json:"count"`
	Rev      string   `json:"rev"`
	Sources  []string `json:"sources"`
}

type manifest struct {
	Version    int      `json:"version"`
	Generated  string   `json:"generated"`
	Categories []string `json:"categories"`
	Presets    []Preset `json:"presets"`
}

var (
	mu         sync.Mutex
	loadedOnce bool
	loaded     manifest
	byName     map[string]Preset
	overlayDir string // "" -> embed only
)

// SetOverlay points the package at a live directory that may hold a
// refreshed manifest.json + *.lst (written by Refresh). Call once at
// startup, before any other call. A dir that doesn't exist yet is fine.
func SetOverlay(dir string) {
	mu.Lock()
	overlayDir = dir
	loadedOnce = false
	mu.Unlock()
}

// readDataFile returns the bytes of one data file ("manifest.json" or
// "<name>.lst"), preferring the overlay and falling back to the embed.
func readDataFile(name string) ([]byte, error) {
	if overlayDir != "" {
		if b, err := os.ReadFile(filepath.Join(overlayDir, name)); err == nil {
			return b, nil
		}
	}
	return files.ReadFile("data/" + name)
}

// snapshot returns the current manifest and name index, loading them on
// first use. The returned values are never mutated in place (Refresh
// swaps in wholly new ones), so callers may read them after the lock is
// dropped.
func snapshot() (manifest, map[string]Preset) {
	mu.Lock()
	defer mu.Unlock()
	if !loadedOnce {
		loadedOnce = true
		loaded = manifest{}
		byName = map[string]Preset{}
		if raw, err := readDataFile("manifest.json"); err == nil {
			var m manifest
			if json.Unmarshal(raw, &m) == nil {
				loaded = m
				idx := make(map[string]Preset, len(m.Presets))
				for _, p := range m.Presets {
					idx[p.Name] = p
				}
				byName = idx
			}
		}
	}
	return loaded, byName
}

// reload forces the next accessor to re-read the manifest (used by
// Refresh after it writes the overlay).
func reload() {
	mu.Lock()
	loadedOnce = false
	mu.Unlock()
}

// Generated is the date stamp of the active manifest ("2006-01-02").
func Generated() string {
	m, _ := snapshot()
	return m.Generated
}

// All returns every preset, sorted by name.
func All() []Preset {
	m, _ := snapshot()
	out := append([]Preset(nil), m.Presets...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// Find returns the preset row for a list id ("youtube" / "youtube-ip").
func Find(name string) (Preset, bool) {
	_, idx := snapshot()
	p, ok := idx[strings.ToLower(strings.TrimSpace(name))]
	return p, ok
}

// Category groups presets for the bot menu.
type Category struct {
	Name    string
	Presets []Preset // domain presets only ("-ip" companions excluded), sorted by title
}

// ByCategory returns the domain presets grouped by category -- categories
// in the manifest's declared order (with any stragglers appended), and
// presets within a category sorted by title. CIDR companions
// ("<svc>-ip") are left out; the UI offers them as a toggle on the
// domain preset via HasCIDR.
func ByCategory() []Category {
	m, _ := snapshot()
	group := map[string][]Preset{}
	var order []string
	for _, p := range m.Presets {
		if p.Kind != "domains" {
			continue
		}
		if _, ok := group[p.Category]; !ok {
			order = append(order, p.Category)
		}
		group[p.Category] = append(group[p.Category], p)
	}

	seq := m.Categories
	if len(seq) == 0 {
		seq = order
	}
	seen := map[string]bool{}
	var cats []Category
	add := func(name string) {
		if seen[name] {
			return
		}
		ps := group[name]
		if len(ps) == 0 {
			return
		}
		seen[name] = true
		sort.Slice(ps, func(a, b int) bool { return ps[a].Title < ps[b].Title })
		cats = append(cats, Category{Name: name, Presets: ps})
	}
	for _, c := range seq {
		add(c)
	}
	for _, c := range order { // any category missing from the declared order
		add(c)
	}
	return cats
}

// HasCIDR reports whether a "<service>-ip" companion list exists for the
// given domain-preset name.
func HasCIDR(name string) bool {
	_, idx := snapshot()
	_, ok := idx[strings.ToLower(strings.TrimSpace(name))+"-ip"]
	return ok
}

// Entries returns the list body for a preset id: domains or CIDRs, one
// per line, comments and blanks stripped. Order is as stored (already
// sorted by the generator).
func Entries(name string) ([]string, bool) {
	_, idx := snapshot()
	name = strings.ToLower(strings.TrimSpace(name))
	if _, ok := idx[name]; !ok {
		return nil, false
	}
	raw, err := readDataFile(name + ".lst")
	if err != nil {
		return nil, false
	}
	var out []string
	for _, ln := range strings.Split(string(raw), "\n") {
		ln = strings.TrimSpace(ln)
		if ln == "" || strings.HasPrefix(ln, "#") {
			continue
		}
		out = append(out, ln)
	}
	return out, true
}
